
def show_help():
    """Show help message"""
    print("minicmd - AI-powered code generation tool")
    print()
    print("Usage:")
    print("  python3 minicmd.py [--claude|--ollama]       # Generate code using AI (default prompt)")
    print("  python3 minicmd.py run [prompt_content] [--claude|--ollama]  # Generate code with optional custom prompt content")
    print("  python3 minicmd.py edit                      # Edit the prompt file")
    print("  python3 minicmd.py add <file>                # Add file reference to prompt")
    print("  python3 minicmd.py config                    # Show current configuration")
    print("  python3 minicmd.py config <key> <value>      # Set configuration value")
    print()
    print("Options:")
    print("  --claude    Use Claude API (requires API key)")
    print("  --ollama    Use Ollama API (requires local Ollama)")
    print()
    print("Configuration keys:")
    print("  default_provider    Default AI provider (claude or ollama)")
    print("  anthropic_api_key      Claude API key")
    print("  claude_model        Claude model name")
    print("  ollama_url          Ollama API URL")
    print("  ollama_model        Ollama model name")
    print()
    print("Examples:")
    print("  python3 minicmd.py config anthropic_api_key sk-ant-...")
    print("  python3 minicmd.py config default_provider claude")
    print("  python3 minicmd.py --claude")
    print("  python3 minicmd.py run")
    print("  python3 minicmd.py run \"create a hello world function\"")
    print("  python3 minicmd.py run \"write a Python calculator\" --claude")
    print("  python3 minicmd.py add minicmd.py")
