
def show_help():
    """Show help message"""
    print("minicmd - AI-powered code generation tool")
    print()
    print("Usage:")
    print("  python3 minicmd.py run [prompt_content] [--claude|--ollama|--deepseek]  # Generate code with optional custom prompt content")
    print("  python3 minicmd.py edit                      # Edit the prompt file")
    print("  python3 minicmd.py add <file>                # Add file reference to prompt")
    print("  python3 minicmd.py list                      # List current attachments")
    print("  python3 minicmd.py config                    # Show current configuration")
    print("  python3 minicmd.py config <key> <value>      # Set configuration value")
    print()
    print("Options:")
    print("  --claude    Use Claude API (requires API key)")
    print("  --ollama    Use Ollama API (requires local Ollama)")
    print("  --deepseek  Use DeepSeek API (requires API key)")
    print("  --verbose, -v    Print verbose output")
    print("  --debug, -d      Print debug output (includes verbose and raw API response)")
    print()
    print("Configuration keys:")
    print("  default_provider    Default AI provider (claude, ollama, or deepseek)")
    print("  anthropic_api_key   Claude API key")
    print("  deepseek_api_key    DeepSeek API key")
    print("  claude_model        Claude model name")
    print("  ollama_url          Ollama API URL")
    print("  ollama_model        Ollama model name")
    print("  deepseek_url        DeepSeek API URL")
    print("  deepseek_model      DeepSeek model name")
    print()
    print("Examples:")
    print("  python3 minicmd.py config anthropic_api_key sk-ant-...")
    print("  python3 minicmd.py config deepseek_api_key sk-...")
    print("  python3 minicmd.py config default_provider deepseek")
    print("  python3 minicmd.py --deepseek")
    print("  python3 minicmd.py run")
    print("  python3 minicmd.py run \"create a hello world function\"")
    print("  python3 minicmd.py run \"write a Python calculator\" --deepseek")
    print("  python3 minicmd.py run --verbose")
    print("  python3 minicmd.py run --debug")
    print("  python3 minicmd.py add minicmd.py")
    print("  python3 minicmd.py list")
