package commands

import (
	"fmt"
)

func ShowHelp() {
	fmt.Println("minicmd - AI-powered code generation tool")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println("  minicmd run [prompt_content] [--claude|--ollama|--deepseek]  # Generate code with optional custom prompt content")
	fmt.Println("  minicmd edit                      # Edit the prompt file")
	fmt.Println("  minicmd read <file>               # Add file reference to prompt")
	fmt.Println("  minicmd list                      # List current attachments")
	fmt.Println("  minicmd clear                     # Clear prompt and attachments")
	fmt.Println("  minicmd showlast                  # Show last AI response")
	fmt.Println("  minicmd config                    # Show current configuration")
	fmt.Println("  minicmd config <key> <value>      # Set configuration value")
	fmt.Println()
	fmt.Println("Options:")
	fmt.Println("  --claude    Use Claude API (requires API key)")
	fmt.Println("  --ollama    Use Ollama API (requires local Ollama)")
	fmt.Println("  --deepseek  Use DeepSeek API (requires API key)")
	fmt.Println("  --verbose, -v    Print verbose output")
	fmt.Println("  --debug, -d      Print debug output (includes verbose and raw API response)")
	fmt.Println("  --safe, -s       Add .new suffix to generated files")
	fmt.Println()
	fmt.Println("Configuration keys:")
	fmt.Println("  default_provider    Default AI provider (claude, ollama, or deepseek)")
	fmt.Println("  anthropic_api_key   Claude API key")
	fmt.Println("  deepseek_api_key    DeepSeek API key")
	fmt.Println("  claude_model        Claude model name")
	fmt.Println("  ollama_url          Ollama API URL")
	fmt.Println("  ollama_model        Ollama model name")
	fmt.Println("  deepseek_url        DeepSeek API URL")
	fmt.Println("  deepseek_model      DeepSeek model name")
	fmt.Println()
	fmt.Println("Examples:")
	fmt.Println("  minicmd config anthropic_api_key sk-ant-...")
	fmt.Println("  minicmd config deepseek_api_key sk-...")
	fmt.Println("  minicmd config default_provider deepseek")
	fmt.Println("  minicmd --deepseek")
	fmt.Println("  minicmd run")
	fmt.Println("  minicmd run \"create a hello world function\"")
	fmt.Println("  minicmd run \"write a Python calculator\" --deepseek")
	fmt.Println("  minicmd run --verbose")
	fmt.Println("  minicmd run --debug")
	fmt.Println("  minicmd run --safe")
	fmt.Println("  minicmd read minicmd.go")
	fmt.Println("  minicmd list")
	fmt.Println("  minicmd showlast")
}
